[package]
name = "egui-miniquad"
version = "0.8.0"
authors = ["Logachev Fedor <not.fl3@gmail.com>", "Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "Bindings between egui and miniquad"
edition = "2021"
rust-version = "1.56"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/not-fl3/egui-miniquad"
repository = "https://github.com/not-fl3/egui-miniquad"
categories = ["gui", "game-development"]
keywords = ["gui", "imgui", "immediate", "portable", "gamedev"]
include = [
  "../LICENSE-APACHE",
  "../LICENSE-MIT",
  "**/*.rs",
  "Cargo.toml",
]

[dependencies]
bytemuck = "1.7"
egui = { version = "0.17.0", features = ["convert_bytemuck"] }
miniquad = { version = "=0.3.0-alpha.43" }
quad-url = "0.1.0"

# https://github.com/not-fl3/miniquad/issues/172
[target.'cfg(target_os = "macos")'.dependencies]
copypasta = "0.7"

[dev-dependencies]
egui_demo_lib = { version = "0.17.0", default-features = false }
glam = "0.20"

[profile.release]
opt-level = 2 # fast and small wasm
