[package]
name = "egui-miniquad"
version = "0.1.0"
authors = ["Logachev Fedor <not.fl3@gmail.com>", "Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "Bindings between egui and miniquad"
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/not-fl3/egui-miniquad"
repository = "https://github.com/not-fl3/egui-miniquad"
categories = ["gui", "game-development"]
keywords = ["gui", "imgui", "immediate", "portable", "gamedev"]
include = [
  "../LICENSE-APACHE",
  "../LICENSE-MIT",
  "**/*.rs",
  "Cargo.toml",
]

[dependencies]
egui = "0.10.0"
miniquad = { version = "=0.3.0-alpha.27" }

# https://github.com/not-fl3/miniquad/issues/172
[target.'cfg(target_os = "macos")'.dependencies]
copypasta = "0.7"

# For compiling natively:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
webbrowser = "0.5"

[dev-dependencies]
egui_demo_lib = "0.10.0" # For example

[profile.release]
opt-level = 2 # fast and small wasm
