[package]
name = "egui-miniquad-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.92"
quote = "1.0.38"
syn = { version = "2.0.93", features = ["full"] }

[lib]
proc-macro = true
